### ISSUE TITLE
Instead of using `ignore_disks` a whitelisting _and_ blacklisting should be possible

### ISSUE THREAD

**Issue by schakko** [dreitier/cloudmon#5]
At the moment, *cloudmon* assumes that each disk inside a connected provider (like all S3 buckets in an AWS account) should be monitored. The parameter `ignore_disks` restricts the disks inside a provider.

A more practical use case would be, that some white-/gray-/blacklisting is implemented:

# Use cases
## UC1
```
disks:
  exclude:
  - bucket-1
```

This would ignore `bucket-1` but include each other disk. This is just a renaming from the current `ignore_disks` configuration key.

## UC2
```
disks:
  exclude:
  - bucket-1
  include:
  - bucket-2
  # all_others is by default set to "include" as this is default behaviour at the moment
  all_others: include
```

and 
```
disks:
  exclude:
  - bucket-1
  include:
  - bucket-2
```

Both UCs would ignore `bucket-1`, explicitly include `bucket-2` and include each other disk (due to the implicit `disks.all_others=include`).

## UC3
```
disks:
  exclude:
  - bucket-1
  include:
  - bucket-2
  all_others: exclude
```

This would implicitly exclude `bucket-1`, include `bucket-2` and exclude each other disk

## UC4
```
disks:
  exclude:
  - bucket-2
  include:
  - bucket-1
  - bucket-2
  all_others: exclude
```

This would include `bucket-1`, exclude `bucket-2` (due to the conflict and `all_others=exclude`) and exclude each other disk

# Required changes
- [ ] Additional configuration keys `disks.include`, `disks.exclude` and `disks.all_others` are added
- [ ] If the old `ignore_disks` is present, *cloudmon* will not start and inform the user that this option is deprecated and has to be moved to `disks.exclude`
- [ ] If an `exclude` statement conlficts with an `include` statement (e.g. `bucket-1` is present in both configuration keys), `all_others` is applied
- [ ] During the discovery phase, the disks are included/excluded based upon the active configuration
- [ ] Documentation has been updated with new configuration keys
