### ISSUE TITLE
Drop the need IAM permission `ListAllMyBuckets` when using S3 storage provider

### ISSUE THREAD

**Issue by schakko** [dreitier/cloudmon#9]
At the moment, the permission `ListAllMyBuckets` must be assigned to the cloudmon user's IAM policy to find the disks. Due to AWS restrictions, either all S3 buckets can be seen or none. This might be a security issue due to leaking of information.

# Use cases
## UC1
```
disks:
  exclude:
    - bucket-1
environments:
  my_aws:
    # auto_discover_disks is enabled by default; this could be dropped
    auto_discover_disks: true
```
This is the default behaviour. `bucket-1` would be excluded but all other disks/S3 buckets are included

## UC2
```
disks:
  exclude:
    - bucket-1
environments:
  my_aws:
    auto_discover_disks: false
```
As auto discovery of disks is disabled, and no disk has been included, no disk/S3 bucket would be found. The `disks.exclude` parameter can be omitted.

## UC3
```
disks:
  include:
    - bucket-2
  exclude:
    - bucket-1
environments:
  my_aws:
    auto_discover_disks: false
```
As auto discovery of disks is disabled, only the disks/S3 buckets below `disks.include` are used. The `disks.exclude` parameter can be omitted.

# Required changes
- [x] S3 storage provider option `environments[].auto_discover_disks: bool(default: true)` added.
- [x] Documentation has been updated (*Storage > AWS S3 > Additional section below "IAM policy"*)
